version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y && yum install -y zip
  build:
    commands:
      - echo "Zipping source files..."
      - zip -r artifact.zip src
      - echo "Uploading artifact to S3..."
      - aws s3 cp artifact.zip s3://test-bucket1101-yamahiro/artifact.zip
  post_build:
    commands:
      - echo "Registering application revision..."
      - aws deploy register-application-revision \
          --application-name kadai \
          --s3-location bucket=test-bucket1101-yamahiro,key=artifact.zip,bundleType=zip
      - echo "Starting deployment..."
      - aws deploy create-deployment \
          --application-name kadai \
          --deployment-group-name kadai-group \
          --s3-location bucket=test-bucket1101-yamahiro,key=artifact.zip,bundleType=zip
artifacts:
  files:
    - artifact.zip
