version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name XXX arn:aws:s3:::test-bucket1101-yamahiro s3://XXX/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src